---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bgd
  namespace: openshift-gitops
spec:
  project: default
  source:
    path: app/overlays/default/
    repoURL: https://github.com/jayhowell/bgd
    targetRevision: main
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
