kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: bgd-route
  namespace: bgd
  labels:
    app: bgd
    app.kubernetes.io/instance: bgd
spec:
  to:
    kind: Service
    name: bgd
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
